### ISSUE TITLE
JSON error after submitting query in Firefox

### ISSUE THREAD

**Issue by z4am** [miclol/WCANotifier#1]
Instead of expected success message, page returned:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Steps to reproduce:
1. Go to https://miclol.github.io/WCANotifier/
2. Enter email, 3x3x3 Cube, 3x3x3 Blindfold, San Ramon, CA, USA, 50km radius, across county borders = No, no fee limit, start date = today
3. Verify reCAPTCHA, submit query

MacOS 13.3.1, FireFox 112.0.2

Retried with Safari 16.4 and received the following message:
Please verify your email of a request you made before before making more requests.

This indicated the previous request did go through and I did find a verification email. Clicking the verification link defaulted to Firefox which returned the same error:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Subsequently using the verification link in Safari returned:
You have already been verified!

So it appears that registration and verification via Firefox are working, but returning the JSON error.

Retried in Firefox with all extensions disabled and using a new city, but got the same error message.
Retried registration and verification in Safari and it works as expected with:
Thank you for verifying your email. You will now recieve notifications. 
Note that receive is spelled incorrectly there :)

**Comment by miclol** [comment]
Changed response header from "application/json" to "text/html".
